### ISSUE TITLE
Build App Example

### ISSUE THREAD

**Issue by elninho22** [CodeMinion/another_brother#15]
please help me

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_blue:generateDebugProto'.
> Could not resolve all files for configuration ':flutter_blue:protobufToolsLocator_protoc'.
   > Could not find protoc-3.11.4-osx-aarch_64.exe (com.google.protobuf:protoc:3.11.4).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/protobuf/protoc/3.11.4/protoc-3.11.4-osx-aarch_64.exe

**Comment by CodeMinion** [comment]
Hello @elninho22 ,

Thank for the additional information! I have just released version 0.0.25 of another_brother which will use Maven Central instead of JCenter for the dependencies on Android, so this error is now fixed there. 

You may also pull the latest version here as well for the fix. I'll go ahead and close this issue but please feel free to open it again if you still encounter the issue after the update. 

Thanks again!

**Comment by elninho22** [comment]
Thank you very much for your commitment to the resolution.

**Comment by mikhael28** [comment]
This same issue is still going on today, with 0.0.25
`flutter run
Using hardware rendering with device
Android SDK built for arm64. If you notice
graphics artifacts, consider enabling
software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK
built for arm64 in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'...    FAILURE: Build failed with an exception.
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'...    * What went wrong:
Running Gradle task 'assembleDebug'...    Execution failed for task ':flutter_blue:generateDebugProto'.
Running Gradle task 'assembleDebug'...    > Could not resolve all files for configuration ':flutter_blue:protobufToolsLocator_protoc'.
Running Gradle task 'assembleDebug'...       > Could not find protoc-3.11.4-osx-aarch_64.exe (com.google.protobuf:protoc:3.11.4).
Running Gradle task 'assembleDebug'...         Searched in the following locations:
Running Gradle task 'assembleDebug'...             https://jcenter.bintray.com/com/google/protobuf/protoc/3.11.4/protoc-3.11.4-osx-aarch_64.exe
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'...    * Try:
Running Gradle task 'assembleDebug'...    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'...    * Get more help at https://help.gradle.org
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'...    BUILD FAILED in 705ms
Running Gradle task 'assembleDebug'...                           1,295ms
Exception: Gradle task assembleDebug failed with exit code 1`

running on an m1 mac

**Comment by mikhael28** [comment]
Any suggestions?

**Comment by CodeMinion** [comment]
Hey @mikhael28 ! Thanks for reaching out about this. This is an issue with the flutter_blu lib, so in order to resolve it on your project you'll open the Android version of your project on Android and after it's done synching open the flutter_blue folder and perform the changes suggested by @elninho22 above. I have been able to confirm that updating the protobuf library to 3.17.3 on will solve this for you on the M1.

Hope this helps but don't hesitate to reach out any time.
